spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jdbc_db
    username: postgres
    password: postgres
logging:
  level:
    '[org.springframework.jdbc.core]': debug
    '[com.example.employeemanagement]': debug
